name: test_master_branch

on:
  push:
    branches: [ add-github-action ]
  pull_request:
    branches: [ add-github-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev
    - uses: actions/checkout@v1
    - name: make
      run: cd file_server/ && make
    - name: Run Test
      run: make test
