name: test_master_branch

on:
  push:
    branches: [ patch-file-server ]
  pull_request:
    branches: [ patch-file-server ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make
    - name: Install jsoncpp manually
      run: sudo apt-get install libjsoncpp-dev
    - uses: actions/checkout@v1
    - name: build
      run: cd file_server/ && cmake . && make
    - name: Run Test
      run: cd file_server/ && sudo ./fs_server_test
